name: surucu_check
description: "SürücüCheck tətbiqi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  flutter_plugin_android_lifecycle: ^2.0.28
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.7.11
  firebase_storage: ^11.6.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  http: ^0.13.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.png
    - assets/logo1.gif
    - assets/images/default_user.png
    - assets/drivers.json
    - assets/default_driver.png

  fonts:
    - family: GaboDrive
      fonts:
        - asset: fonts/GaboDrive Condensed Bold.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # <-- ikon faylının yolu